# `Tensorflow2.0`基本数据类型


In [1]:
import tensorflow as tf


In [2]:
tf.constant(1)

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(2.)

<tf.Tensor: id=10, shape=(), dtype=float32, numpy=2.0>

In [4]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: id=28, shape=(), dtype=float64, numpy=2.0>

In [5]:
tf.constant([True, False])

<tf.Tensor: id=54, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [6]:
tf.constant('Hello')

<tf.Tensor: id=86, shape=(), dtype=string, numpy=b'Hello'>

## 数据属性


In [7]:
with tf.device('cpu'):
    a = tf.constant([1])

with tf.device('gpu'):
    b = tf.range(4)
    

In [8]:
print("device of a: ", a.device)
print("device of b: ", b.device)


device of a:  /job:localhost/replica:0/task:0/device:CPU:0
device of b:  /job:localhost/replica:0/task:0/device:GPU:0


In [9]:
# cpu <=> gpu, 
aa = a.gpu()
bb = b.cpu()

print("device of aa: ", aa.device)
print("device of bb: ", bb.device)



device of aa:  /job:localhost/replica:0/task:0/device:GPU:0
device of bb:  /job:localhost/replica:0/task:0/device:CPU:0


In [10]:
# tensor => numpy
b.numpy()


array([0, 1, 2, 3])

In [11]:
print("scalar type of b ndims: ", b.ndim)
print("tensor type of b ranks: ", tf.rank(b))
print("name of b: ", b.name)


scalar type of b ndims:  1
tensor type of b ranks:  tf.Tensor(1, shape=(), dtype=int32)


AttributeError: Tensor.name is meaningless when eager execution is enabled.

In [12]:
# check is_tensor
print("a is a tensor: ", isinstance(a, tf.Tensor))
print("a is a tensor: ", tf.is_tensor(a))


a is a tensor:  True
a is a tensor:  True


In [2]:
# Data convert 
import numpy as np

e = np.arange(5)
print("e:", e)
print("dtype of e:", e.dtype)

ee = tf.convert_to_tensor(e)
print("ee:", e)


e: [0 1 2 3 4]
dtype of e: int32
ee: [0 1 2 3 4]


In [14]:
tf.cast(ee, dtype=tf.float32)


<tf.Tensor: id=429, shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [15]:
tf.cast(ee, dtype=tf.double)


<tf.Tensor: id=481, shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

### bool <=> int


In [16]:
t = tf.constant([0 ,1])
tf.cast(t, dtype=tf.bool)


<tf.Tensor: id=540, shape=(2,), dtype=bool, numpy=array([False,  True])>

In [17]:
tt = tf.cast(t, dtype=tf.bool)
tf.cast(tt, dtype=tf.int32)


<tf.Tensor: id=609, shape=(2,), dtype=int32, numpy=array([0, 1])>

### `tf.Variable`：在`tensor`基础上可求导


In [19]:
d = tf.range(5)
dv = tf.Variable(d)

print("dtype of dv: ", dv.dtype)
print("name of dv: ", dv.name)
print("is_trainable of dv: ", dv.trainable)


dtype of dv:  <dtype: 'int32'>
name of dv:  Variable:0
is_trainable of dv:  True


In [20]:
print("dv is Tensor: ", isinstance(dv, tf.Tensor))
print("dv is Variable: ", isinstance(dv, tf.Variable))
tf.is_tensor(dv)


dv is Tensor:  False
dv is Variable:  True


True

## 创建`Tensor`

- from numpy, list
- tf.zeros, tf.zeros_like, tf.ones, 
- tf.fill
- tf.random
- tf.constant


In [21]:
a = tf.convert_to_tensor(np.ones([2, 3]))
b = tf.convert_to_tensor([2., 3.])


In [22]:
tf.zeros([])
tf.zeros([2, 2])


<tf.Tensor: id=1027, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [23]:
tf.fill([2, 2], 4.)


<tf.Tensor: id=1115, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [24]:
tf.random.normal([2, 2], mean=1, stddev=1)


<tf.Tensor: id=1212, shape=(2, 2), dtype=float32, numpy=
array([[ 1.1985031, -0.826035 ],
       [ 3.1260815,  1.2006266]], dtype=float32)>

In [25]:
# 截断分布，防止梯度消失
tf.random.truncated_normal([2, 2], mean=0, stddev=1)


<tf.Tensor: id=1317, shape=(2, 2), dtype=float32, numpy=
array([[ 1.2507284 , -0.09851211],
       [ 0.6073443 , -1.8210297 ]], dtype=float32)>

In [26]:
# 均匀分布
tf.random.uniform([2, 2], minval=0, maxval=5)


<tf.Tensor: id=1429, shape=(2, 2), dtype=float32, numpy=
array([[2.897038 , 4.3528013],
       [0.9034705, 4.5873365]], dtype=float32)>

In [27]:
# random permutation: 随机打散
idx = tf.range(10)
idx = tf.random.shuffle(idx)

a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)

a = tf.gather(a, idx)
b = tf.gather(b, idx)



### 1. 常量的使用


In [28]:
out = tf.random.uniform([4, 10])
print("out: ", out)

out:  tf.Tensor(
[[4.9648392e-01 5.3804338e-01 1.1848235e-01 9.8715699e-01 7.6896358e-01
  8.1761205e-01 1.9997239e-02 3.5519218e-01 9.7572947e-01 2.3420095e-01]
 [3.8370979e-01 1.1830878e-01 5.5359900e-01 3.5739303e-02 1.3182354e-01
  1.1041224e-01 5.7361424e-01 4.2505956e-01 1.9017565e-01 7.8445935e-01]
 [3.2520294e-04 2.2230685e-01 3.8391459e-01 7.1896875e-01 9.3840337e-01
  2.9250014e-01 9.2271006e-01 4.1293383e-01 5.6773770e-01 7.8036439e-01]
 [5.2806425e-01 1.9349170e-01 6.9213891e-01 5.2110004e-01 6.7373466e-01
  1.9295335e-02 7.7046812e-01 2.4521136e-01 2.5076437e-01 6.9201708e-01]], shape=(4, 10), dtype=float32)


In [29]:
y = tf.range(4)
y = tf.one_hot(y, depth=10)
print("pred y: ", y)


pred y:  tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [30]:
loss = tf.keras.losses.mse(y, out)
print("loss: ", loss)


loss:  tf.Tensor([0.392479   0.24231823 0.3865258  0.26745033], shape=(4,), dtype=float32)


In [31]:
tf.reduce_mean(loss)


<tf.Tensor: id=2042, shape=(), dtype=float32, numpy=0.32219332>

### 2. 3d tensor 

- nlp, sentence: [batch, seq_len, word_dim]

In [3]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)


17465344/17464789 [==============================] - 2s 0us/step


In [4]:
x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, maxlen=80)
print("x_train shape: ", x_train.shape)


x_train shape:  (25000, 80)


### 3. 4d tensor

-cv, image: [batch, h, w, channels]


In [5]:
x = tf.random.normal((4, 32, 32, 3))
net = tf.keras.layers.Conv2D(16, kernel_size=3)
net(x)


<tf.Tensor: id=41, shape=(4, 30, 30, 16), dtype=float32, numpy=
array([[[[ 6.35303378e-01,  3.36781770e-01, -3.29926401e-01, ...,
          -2.16325521e-02,  6.10602498e-01, -4.72451329e-01],
         [ 3.41860980e-01,  1.41850561e-01,  5.76126724e-02, ...,
          -6.33215487e-01, -3.86410952e-01,  1.30264694e-02],
         [-6.56270266e-01, -4.55143541e-01,  1.01047230e+00, ...,
           2.19156995e-01,  1.14553237e+00, -4.46844757e-01],
         ...,
         [ 4.96770293e-02, -2.31059149e-01,  2.21819580e-01, ...,
          -3.44803035e-01, -1.02263594e+00, -2.59762645e-01],
         [ 3.49010974e-01, -3.13734382e-01,  1.09137536e-03, ...,
          -1.13431859e+00,  3.37371230e-01, -7.35397160e-01],
         [-7.55613267e-01, -1.42647707e+00,  3.34408879e-01, ...,
           4.69449103e-01, -1.42016101e+00, -9.46678638e-01]],

        [[-3.33803892e-02, -3.66623610e-01,  7.92861700e-01, ...,
           2.84674019e-01,  3.91784668e-01,  4.90013093e-01],
         [-5.17160706e-0

### 4. 5d tensor

- single task: [b, h, w, 3]
- meta-learning: [task-b, b, h, w, 3]


## `Tensor`操作：索引和切片


In [6]:
# 1. basic indexing
a = tf.ones([1, 4, 4, 3])


In [7]:
a[0][0]


<tf.Tensor: id=79, shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
a[0][0][0]


<tf.Tensor: id=114, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [9]:
a[0][0][0][1]


<tf.Tensor: id=161, shape=(), dtype=float32, numpy=1.0>

In [10]:
# 2. numpy style indexing
b = tf.random.normal([4, 28, 28, 3])
b[1].shape


TensorShape([28, 28, 3])

In [11]:
b[1, 2].shape

TensorShape([28, 3])

In [12]:
b[1, 2, 2, 1].shape

TensorShape([])

In [13]:
# 3. start:end:step, ::step, ::-1(倒序), ...()
c = tf.range(10)
c[-3:]


<tf.Tensor: id=326, shape=(3,), dtype=int32, numpy=array([7, 8, 9])>

### Selective indexing

- tf.gather
- tf.gather_nd
- tf.boolean_mask


In [14]:
# a = [classes, students, scores]
a = tf.random.uniform([4, 35, 9], maxval=100, dtype=tf.int32)



In [15]:
tf.gather(a, axis=0, indices=[1, 3]).shape


TensorShape([2, 35, 9])

In [16]:
tf.gather(a, axis=2, indices=[2, 3, 5]).shape

TensorShape([4, 35, 3])

In [17]:
# [cls1_stu1, cls2_stu2, cls3_stu3, cls4_stu4]
tf.gather_nd(a, [[0, 0], [1, 1], [2, 2], [3, 3]]).shape


TensorShape([4, 9])

In [18]:
c = tf.random.normal([4, 28, 28, 3], mean=1, stddev=1)
print(c.shape)



(4, 28, 28, 3)


In [19]:
# tf.boolean_mask
tf.boolean_mask(c, mask=[True, False, False, True], axis=0).shape



W0720 20:40:58.197344  8164 deprecation.py:323] From d:\programs\conda\envs\gpu-env\lib\site-packages\tensorflow\python\ops\array_ops.py:1340: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


TensorShape([2, 28, 28, 3])

In [21]:
cc = tf.ones([2, 3, 4])
tf.boolean_mask(cc, mask=[[True, False, False], [False, True, False]])


<tf.Tensor: id=738, shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

## 维度变换

- shape, ndim
- reshape
- expand


In [22]:
# 1. tf.transpose

aa = tf.random.normal([4, 28, 28, 3])
tf.transpose(aa, [0, 3, 1, 2]).shape



TensorShape([4, 3, 28, 28])

In [23]:
# expand 
# a: [classes, student, subjects]
aa = tf.random.uniform([4, 28, 4])
print(tf.expand_dims(aa, axis=0).shape)
print(tf.expand_dims(aa, axis=3).shape)
print(tf.expand_dims(aa, axis=-1).shape)


(1, 4, 28, 4)
(4, 28, 4, 1)
(4, 28, 4, 1)


In [24]:
# squeeze
# 减少 features 为 1 的维度
print(tf.squeeze(tf.zeros([1, 2, 1, 1, 3])).shape)


(2, 3)


In [25]:
print(tf.squeeze(tf.zeros([1, 2, 1, 1, 3]), axis=0).shape)


(2, 1, 1, 3)


## Broadcasting

- expand
- without coping data (vs tf.tile)
- tf.broadcast_to

**`Key Idea`**

1. insert 1 dim ahead if needed
2. Expand dims with size 1 to same size
3. Feature map: [4, 32, 32, 3]
4. Bias: [3] -> [1, 1, 1, 3] -> [4, 32, 32, 3]


**broadcast 好处**

- for real demanding(简洁)
- memory consumption(节省空间)
