# 数学运算

- +-*/
- **, pow, square 


## Operation type

- element-wise: +-*?
- matrix-wise: @, matmul
- dim-wise: reduce_mean/max/min/sum


In [1]:
import tensorflow as tf
from tensorflow import keras


In [2]:
a = tf.ones([2, 2])
b = tf.fill([2, 2], 2.)

a+b, a-b, a*b, a/b


(<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: id=7, shape=(2, 2), dtype=float32, numpy=
 array([[-1., -1.],
        [-1., -1.]], dtype=float32)>,
 <tf.Tensor: id=8, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: id=9, shape=(2, 2), dtype=float32, numpy=
 array([[0.5, 0.5],
        [0.5, 0.5]], dtype=float32)>)

In [3]:
b//a, b%a 


(<tf.Tensor: id=50, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: id=51, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

In [4]:
a, b 


(<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>)

In [7]:
tf.matmul(a, b)


InternalError: Blas GEMM launch failed : a.shape=(2, 2), b.shape=(2, 2), m=2, n=2, k=2 [Op:MatMul] name: MatMul/

In [2]:
a = tf.ones([4, 2, 3])
b = tf.fill([4, 3, 5], 2.)

print(a@b)


tf.Tensor(
[[[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]], shape=(4, 2, 5), dtype=float32)


In [3]:
# with broadcasting
b = tf.fill([3, 5], 3.)
print(a.shape)
print(b.shape)


(4, 2, 3)
(3, 5)


In [4]:
bb = tf.broadcast_to(b, [4, 3, 5])

a@bb


<tf.Tensor: id=21, shape=(4, 2, 5), dtype=float32, numpy=
array([[[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]]], dtype=float32)>

## 前向传播运算

