# 数学运算

- +-*/
- **, pow, square 


## Operation type

- element-wise: +-*?
- matrix-wise: @, matmul
- dim-wise: reduce_mean/max/min/sum


In [1]:
import tensorflow as tf
from tensorflow import keras


In [2]:
a = tf.ones([2, 2])
b = tf.fill([2, 2], 2.)

a+b, a-b, a*b, a/b


(<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: id=7, shape=(2, 2), dtype=float32, numpy=
 array([[-1., -1.],
        [-1., -1.]], dtype=float32)>,
 <tf.Tensor: id=8, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: id=9, shape=(2, 2), dtype=float32, numpy=
 array([[0.5, 0.5],
        [0.5, 0.5]], dtype=float32)>)

In [3]:
b//a, b%a 


(<tf.Tensor: id=50, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: id=51, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

In [4]:
a, b 


(<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>)

In [7]:
tf.matmul(a, b)


InternalError: Blas GEMM launch failed : a.shape=(2, 2), b.shape=(2, 2), m=2, n=2, k=2 [Op:MatMul] name: MatMul/

In [2]:
a = tf.ones([4, 2, 3])
b = tf.fill([4, 3, 5], 2.)

print(a@b)


tf.Tensor(
[[[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]], shape=(4, 2, 5), dtype=float32)


In [3]:
# with broadcasting
b = tf.fill([3, 5], 3.)
print(a.shape)
print(b.shape)


(4, 2, 3)
(3, 5)


In [4]:
bb = tf.broadcast_to(b, [4, 3, 5])

a@bb


<tf.Tensor: id=21, shape=(4, 2, 5), dtype=float32, numpy=
array([[[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]]], dtype=float32)>

## 前向传播运算


## 合并与分割

- tf.concat
- tf.split
- tf.stack : create new dim
- tf.unstack


In [2]:
a = tf.ones([4, 35, 8])
b = tf.ones([2, 35, 8])

c = tf.concat([a, b], axis=0)
c.shape


TensorShape([6, 35, 8])

In [3]:
a = tf.ones([4, 32, 8])
b = tf.ones([4, 3, 8])

c = tf.concat([a, b], axis=1)
c.shape


TensorShape([4, 35, 8])

In [4]:
a = tf.ones([4, 32, 8])
b = tf.ones([4, 32, 8])

c = tf.stack([a, b], axis=0)
c.shape


TensorShape([2, 4, 32, 8])

In [5]:
# split
c = tf.ones([2, 4, 35, 8])
res = tf.unstack(c, axis=3)
print("unstack c return %s elements"%len(res))

res2 = tf.split(c, num_or_size_splits=2)
print("split c return %s elements"%len(res2))


unstack c return 8 elements
split c return 2 elements


In [7]:
res3 = tf.split(c, axis=3, num_or_size_splits=[2, 2, 4])
print("res3 shape is : ", res3[0].shape, res3[1].shape, res3[2].shape)



res3 shape is :  (2, 4, 35, 2) (2, 4, 35, 2) (2, 4, 35, 4)


## 数据统计

- vector norm: L2, L1



In [2]:
a = tf.ones([2, 2])
print("norm(L2) of a: ", tf.norm(a))
print("norm(L2) of a: ", tf.sqrt(tf.reduce_sum(tf.square(a))))



norm(L2) of a:  tf.Tensor(2.0, shape=(), dtype=float32)
norm(L2) of a:  tf.Tensor(2.0, shape=(), dtype=float32)


In [3]:
print("norm(L2) of a on axis 1", tf.norm(a, ord=2, axis=1))
print("norm(L1) of a ", tf.norm(a, ord=1))


norm(L2) of a on axis 1 tf.Tensor([1.4142135 1.4142135], shape=(2,), dtype=float32)
norm(L1) of a  tf.Tensor(4.0, shape=(), dtype=float32)


In [4]:
b = tf.random.normal([4, 10])
print("min of b: ", tf.reduce_min(b))
print("max of b: ", tf.reduce_max(b))
print("sum of b: ", tf.reduce_sum(b))



min of b:  tf.Tensor(-1.7640504, shape=(), dtype=float32)
max of b:  tf.Tensor(1.5654981, shape=(), dtype=float32)
sum of b:  tf.Tensor(-0.91320515, shape=(), dtype=float32)


In [5]:
print("min of b on axis=1: ", tf.reduce_min(b, axis=1))
print("max of b on axis=1: ", tf.reduce_max(b, axis=1))
print("sum of b on axis=1: ", tf.reduce_sum(b, axis=1))


min of b on axis=1:  tf.Tensor([-1.3314389  -0.87622225 -1.7640504  -0.8846502 ], shape=(4,), dtype=float32)
max of b on axis=1:  tf.Tensor([1.5654981 0.9704872 1.4989897 1.3365887], shape=(4,), dtype=float32)
sum of b on axis=1:  tf.Tensor([-0.70662004 -0.4892643  -0.92424476  1.206924  ], shape=(4,), dtype=float32)


In [6]:
print("max args of b: ", tf.argmax(b))
print("shape of b' argmax: ", tf.argmax(b).shape)




max args of b:  tf.Tensor([3 0 2 0 3 1 2 3 1 3], shape=(10,), dtype=int64)
shape of b' argmax:  (10,)


In [7]:
c = tf.constant([1, 2, 3, 3, 2])
d = tf.range(5)
print("c equal d is ", tf.equal(c, d))


c equal d is  tf.Tensor([False False False  True False], shape=(5,), dtype=bool)


In [8]:
res = tf.equal(c, d)
tf.reduce_sum(tf.cast(res, dtype=tf.int32))


<tf.Tensor: id=88, shape=(), dtype=int32, numpy=1>

In [9]:
print("unique of c: ", tf.unique(c))


unique of c:  Unique(y=<tf.Tensor: id=108, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>, idx=<tf.Tensor: id=109, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 2, 1])>)


## 张量排序

- Sort/argsort
- TopK
- Top-5 Acc.


In [10]:
a = tf.random.shuffle(tf.range(5))
# 默认的轴为最后一个维度
print("Sort of a : ", tf.sort(a, direction="DESCENDING"))
print("ArgSort of a : ", tf.argsort(a, direction="DESCENDING"))


Sort of a :  tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)
ArgSort of a :  tf.Tensor([4 2 3 1 0], shape=(5,), dtype=int32)


In [11]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
print("A: ", a)


A:  tf.Tensor(
[[9 8 4]
 [5 3 7]
 [0 4 3]], shape=(3, 3), dtype=int32)


In [12]:
res = tf.math.top_k(a, 2)
print("top 2 of a :", res)


top 2 of a : TopKV2(values=<tf.Tensor: id=199, shape=(3, 2), dtype=int32, numpy=
array([[9, 8],
       [7, 5],
       [4, 3]])>, indices=<tf.Tensor: id=200, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 0],
       [1, 2]])>)


**Top K accuracy**

- prob: [0.1, 0.2, 0.3, 0.4]
- label: [2]

then:

- only consider top-1 prediction: [3] : 0%
- only consider top-2 prediction: [3] : 100%
- only consider top-3 prediction: [3] : 100%


In [14]:
def accuracyTopK(output, target, topk=(1,)):
    maxk = max(topk)
    batch_size = target.shape[0]
    
    pred = tf.math.top_k(output, maxk).indices
    pred = tf.transpose(pred, perm=[1, 0])
    target_ = tf.broadcast_to(target, pred.shape)
    correct = tf.equal(pred, target_)
    
    res = []
    for k in topk:
        correct_k = tf.cast(tf.reshape(correct[:k], [-1]), dtype=tf.float32)
        correct_k = tf.reduce_sum(correct_k)
        acc = float(correct_k / batch_size)
        res.append(acc)
    return res


## 数据填充与复制

- tf.pad
- tf.tile: repeat data on special dim
- 


In [15]:
# tf.pad

a = tf.reshape(tf.range(9), [3, 3])
print(a)
print(a.shape)



tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
(3, 3)


In [17]:
print(tf.pad(a, [[1, 0], [1, 0]]))



tf.Tensor(
[[0 0 0 0]
 [0 0 1 2]
 [0 3 4 5]
 [0 6 7 8]], shape=(4, 4), dtype=int32)


In [18]:
# image padding
image = tf.ones([4, 28, 28, 3])
pad_image = tf.pad(image, [[0, 0], [2, 2], [2, 2], [0, 0]])
print("shape of pad_image: ", pad_image.shape)


shape of pad_image:  (4, 32, 32, 3)


In [19]:
tf.tile(a, [1, 2])


<tf.Tensor: id=366, shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

## 张量限幅

- clip_by_value
- relu
- clip_by_norm
- gradient clipping


In [20]:
a = tf.range(10)
print("a is: ", a)


a is:  tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [21]:
# clip, max(2, x)
print("max(2, a) is: ",  tf.maximum(a, 2))
print("min(8, a) is: ",  tf.minimum(a, 8))
print("2 <= a <= 8 is: ",  tf.clip_by_value(a, 2, 8))


max(2, a) is:  tf.Tensor([2 2 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
min(8, a) is:  tf.Tensor([0 1 2 3 4 5 6 7 8 8], shape=(10,), dtype=int32)
2 <= a <= 8 is:  tf.Tensor([2 2 2 3 4 5 6 7 8 8], shape=(10,), dtype=int32)


In [22]:
# clip_by_norm
a = tf.random.normal([2, 2], mean=10)
print("Norm(L2) of a: ", tf.norm(a))
aa = tf.clip_by_norm(a, 16)
print(aa)
print("Norm(L2) of aa: ", tf.norm(aa))


W0723 00:03:09.462687  4060 deprecation.py:323] From d:\programs\conda\envs\gpu-env\lib\site-packages\tensorflow\python\ops\clip_ops.py:157: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Norm(L2) of a:  tf.Tensor(21.092033, shape=(), dtype=float32)
tf.Tensor(
[[7.8172174 7.5813594]
 [8.406377  8.169879 ]], shape=(2, 2), dtype=float32)
Norm(L2) of aa:  tf.Tensor(15.999999, shape=(), dtype=float32)


### Gradient Clipping

1. Gradient Exploding
2. Gradient Vanishing


## 高阶操作

- tf.where
- tf.scatter_nd
- tf.meshgrid


In [23]:
# np.where
a = tf.random.normal([3, 3])
print(a)


tf.Tensor(
[[ 0.2891546   1.2981161  -0.725229  ]
 [-0.9859346   0.9249258   1.6991228 ]
 [-0.24700968 -0.75834703 -0.7539023 ]], shape=(3, 3), dtype=float32)


In [24]:
mask = a > 0
print(mask)


tf.Tensor(
[[ True  True False]
 [False  True  True]
 [False False False]], shape=(3, 3), dtype=bool)


In [25]:
tf.boolean_mask(a, mask)


<tf.Tensor: id=656, shape=(4,), dtype=float32, numpy=array([0.2891546, 1.2981161, 0.9249258, 1.6991228], dtype=float32)>

In [26]:
indices = tf.where(mask)
print(indices)


tf.Tensor(
[[0 0]
 [0 1]
 [1 1]
 [1 2]], shape=(4, 2), dtype=int64)


In [27]:
tf.gather_nd(a, indices)


<tf.Tensor: id=750, shape=(4,), dtype=float32, numpy=array([0.2891546, 1.2981161, 0.9249258, 1.6991228], dtype=float32)>

In [ ]:
# tf.where(cond, A, B) 类似于三元运算： cond ? A : B


In [2]:
indices = tf.constant([[4], [3], [1]])
updates = tf.constant([9, 10, 11])
shape = tf.constant([8])

tf.scatter_nd(indices, updates, shape)


<tf.Tensor: id=3, shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0,  0])>

In [3]:
x = tf.linspace(-2., 2., 5)
y = tf.linspace(-2., 2., 5)

point_x, point_y = tf.meshgrid(x, y)

print(point_x)

tf.Tensor(
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]], shape=(5, 5), dtype=float32)


In [13]:
points = tf.stack([point_x, point_y], axis=2)
print(points)


tf.Tensor(
[[[-2. -2.]
  [-1. -2.]
  [ 0. -2.]
  [ 1. -2.]
  [ 2. -2.]]

 [[-2. -1.]
  [-1. -1.]
  [ 0. -1.]
  [ 1. -1.]
  [ 2. -1.]]

 [[-2.  0.]
  [-1.  0.]
  [ 0.  0.]
  [ 1.  0.]
  [ 2.  0.]]

 [[-2.  1.]
  [-1.  1.]
  [ 0.  1.]
  [ 1.  1.]
  [ 2.  1.]]

 [[-2.  2.]
  [-1.  2.]
  [ 0.  2.]
  [ 1.  2.]
  [ 2.  2.]]], shape=(5, 5, 2), dtype=float32)


In [8]:
tf.math.sin(points[...,0]) + tf.math.sin(points[...,1])


<tf.Tensor: id=240, shape=(5, 5), dtype=float32, numpy=
array([[-1.8185948 , -1.7507684 , -0.9092974 , -0.06782639,  0.        ],
       [-1.7507684 , -1.682942  , -0.841471  ,  0.        ,  0.06782639],
       [-0.9092974 , -0.841471  ,  0.        ,  0.841471  ,  0.9092974 ],
       [-0.06782639,  0.        ,  0.841471  ,  1.682942  ,  1.7507684 ],
       [ 0.        ,  0.06782639,  0.9092974 ,  1.7507684 ,  1.8185948 ]],
      dtype=float32)>