# 序列化数据

- 语言 : [batch, seq_len, feature_dims]



In [1]:
import tensorflow as tf
from tensorflow import keras


In [2]:
x = tf.range(5)
x = tf.random.shuffle(x)
print(x)


tf.Tensor([2 1 3 0 4], shape=(5,), dtype=int32)


In [3]:
# embedding layer
net = keras.layers.Embedding(10, 4) # vocab : 10, dims : 4
net(x)


<tf.Tensor: id=22, shape=(5, 4), dtype=float32, numpy=
array([[-0.03609692,  0.04109354,  0.00898855, -0.02845278],
       [-0.01840137, -0.0363839 ,  0.00360017, -0.04039004],
       [-0.01330985,  0.0114594 ,  0.00912386, -0.02052574],
       [ 0.00583205,  0.00259447, -0.0178232 ,  0.01124288],
       [ 0.00714461, -0.02769746, -0.03048461,  0.00566433]],
      dtype=float32)>

In [4]:
print(net.trainable)
print(net.trainable_variables)


True
[<tf.Variable 'embedding/embeddings:0' shape=(10, 4) dtype=float32, numpy=
array([[ 5.8320537e-03,  2.5944710e-03, -1.7823197e-02,  1.1242878e-02],
       [-1.8401373e-02, -3.6383905e-02,  3.6001690e-03, -4.0390037e-02],
       [-3.6096919e-02,  4.1093539e-02,  8.9885481e-03, -2.8452778e-02],
       [-1.3309848e-02,  1.1459399e-02,  9.1238618e-03, -2.0525742e-02],
       [ 7.1446076e-03, -2.7697457e-02, -3.0484606e-02,  5.6643263e-03],
       [-8.9195147e-03, -1.3125740e-02, -3.3897839e-02,  3.5523985e-02],
       [ 4.4082318e-02, -2.7012695e-02, -8.7805875e-03, -1.0815371e-02],
       [-6.1817095e-04, -3.1836823e-02,  1.5756939e-02,  3.0123200e-02],
       [ 6.0044229e-05, -3.9025545e-03, -2.3969365e-02,  1.0941029e-03],
       [-1.7123438e-02, -2.5464905e-02,  4.7005627e-02, -1.0920882e-02]],
      dtype=float32)>]


## 循环神经网络

- weight sharing
- consistent memory
 
 

In [5]:
cell = keras.layers.SimpleRNNCell(3)
cell.build(input_shape=(None, 4))


In [6]:
cell.trainable_variables


[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.2742194 , -0.678669  ,  0.68380105],
        [-0.3843025 ,  0.0419659 ,  0.1113162 ],
        [-0.7594901 ,  0.01632738, -0.02263504],
        [-0.6028076 , -0.45310733, -0.88365376]], dtype=float32)>,
 <tf.Variable 'recurrent_kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.85576653, -0.09808186, -0.50797975],
        [ 0.26543722,  0.92602444,  0.26836917],
        [ 0.44407952, -0.3644981 ,  0.8184953 ]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]